language: clojure
lein: lein2
env:
  global:
    - AWS_ACCESS_KEY=XXXXXXXXXXXXXXX
    - AWS_SECRET_KEY=YYYYYYYYYYYYYYYYYYYYYY
before_script:
  - ./run_dynamodb_local.sh > /dev/null 2>&1 &
script: lein2 test
jdk:
  - openjdk7
  - oraclejdk7
